name: Check README Links

on:
  schedule:
    - cron: "0 9 * * 1"
  push:
    branches:
      - main
  pull_request:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check links in README.md
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          reporter: github-pr-check
          show_stats: true
